version: "3.7"

networks:
  web:
    external: true

services:  
  traefik:
    image: traefik:2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 9980:9980
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/raimmy/remigerme.xyz/traefik.yml:/traefik.yml
      - /home/raimmy/remigerme.xyz/letsencrypt/acme.json:/letsencrypt/acme.json
    networks:
      - web
