providers:
  docker: {}

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "nowebmaster@remigerme.xyz"
      storage: "/letsencrypt/acme.json"
      entryPoint: "https"
      onHostRule: true
      httpChallenge:
        entryPoint: "http"
