networks:
  web:
    external: true

services:  
  nginx:
    image: nginx:1.25
    container_name: home-nginx
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
      - ./remigerme.xyz.conf:/etc/nginx/conf.d/remigerme.xyz.conf
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.home.rule=Host(`remigerme.xyz`)
      # https configuration
      - traefik.http.routers.home.tls=true
      - traefik.http.routers.home.tls.certresolver=myresolver
      # Connect the reverse proxy to the container port 80
      - traefik.http.services.home.loadbalancer.server.port=80